### ISSUE TITLE
Zerobin won't install itself at the root of a domain

### ISSUE THREAD

**Issue by s0r00t** [julienmalik/zerobin_ynh#7]
Test case :
-Create a second domain (ex :  bin.domain.tld)
-Install Zerobin on it at root (/)
-Go on the domain 

Expected : Zerobin is at the root, like bin.domain.tld
Results : Zerobin is at the root, but when going on bin.domain.tld, it tries to go into /zerobin folder, and so returns a 404.

**Comment by Kloadut** [comment]
Fixed as of 7c3c5fcec405c5c6446ff60f901454b86c8312a2

**Comment by s0r00t** [comment]
Thanks for the fast fix :+1:

**Comment by s0r00t** [comment]
Actually, still not fixed.  
Test case : https://bin.courtial.me/zerobin/

**Comment by Kloadut** [comment]
Try to reinstall

**Comment by s0r00t** [comment]
I did, even a fresh install from the repo... Did not work :/

**Comment by Kloadut** [comment]
Ensure that NGinx is properly restarted and that `yunohost app ssowatconf` worked. It works by my side

**Comment by s0r00t** [comment]
Still doesn't after a nginx -s reload and a ssowatconf.

**Comment by Kloadut** [comment]
What is the content of /etc/nginx/conf.d/YOUR_DOMAIN.d/zerobin.conf ?

**Comment by s0r00t** [comment]
location / {
  alias /var/www/zerobin/ ;
  if ($scheme = http) {
    rewrite ^ https://$server_name$request_uri? permanent;
  }
  index index.php;
  try_files $uri $uri/ index.php;
  location ~ [^/]\.php(/|$) {
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param REMOTE_USER     $remote_user;
    fastcgi_param PATH_INFO       $fastcgi_path_info;
    fastcgi_param SCRIPT_FILENAME $request_filename;
  }

  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
}

**Comment by Kloadut** [comment]
Looks OK.
Your /etc/ssowat/conf.json ?

**Comment by s0r00t** [comment]
{
    "additional_headers": {
        "Auth-User": "uid", 
        "Email": "mail", 
        "Name": "cn", 
        "Remote-User": "uid"
    }, 
    "domains": [
        "courtial.me", 
        "bin.courtial.me", 
        "mail.courtial.me", 
        "rss.courtial.me", 
        "bag.courtial.me", 
        "dav.courtial.me", 
        "baikal.courtial.me"
    ], 
    "portal_domain": "courtial.me", 
    "portal_path": "/yunohost/sso/", 
    "protected_regex": [], 
    "protected_urls": [], 
    "redirected_regex": {
        "courtial.me/yunohost[\\/]?$": "https://courtial.me/yunohost/sso/"
    }, 
    "redirected_urls": {}, 
    "skipped_regex": [], 
    "skipped_urls": [
        "rss.courtial.me/public.php", 
        "rss.courtial.me/api", 
        "baikal.courtial.me", 
        "/yunohost/admin", 
        "/yunohost/api", 
        "/yunohost/admin", 
        "/yunohost/api", 
        "/yunohost/admin", 
        "/yunohost/api", 
        "/yunohost/admin", 
        "/yunohost/api", 
        "/yunohost/admin", 
        "/yunohost/api", 
        "/yunohost/admin", 
        "/yunohost/api", 
        "/yunohost/admin", 
        "/yunohost/api"
    ], 
    "unprotected_regex": [], 
    "unprotected_urls": [
        "bin.courtial.me"
    ], 
    "users": {
        "hugo": {
            "bag.courtial.me/": "Wallabag", 
            "baikal.courtial.me/": "Baikal", 
            "bin.courtial.me/": "Zerobin", 
            "dav.courtial.me/": "AgenDAV", 
            "mail.courtial.me/": "Roundcube", 
            "rss.courtial.me/": "Tiny Tiny RSS"
        }, 
        "thomas": {
            "bag.courtial.me/": "Wallabag", 
            "baikal.courtial.me/": "Baikal", 
            "bin.courtial.me/": "Zerobin", 
            "dav.courtial.me/": "AgenDAV", 
            "mail.courtial.me/": "Roundcube", 
            "rss.courtial.me/": "Tiny Tiny RSS"
        }

**Comment by Kloadut** [comment]
Looks good as well...
